.\" Copyright 2011, 2012, 2026 Zackary Parsons. Licensed under GPLv3.
.TH "KBSH" "1" "MARCH 2026" "kbsh 0.3.0-dev"

.SH NAME

\fBkbsh\fR \- Kept-Bounded Shell

.SH SYNOPSIS

\fBkbsh\fR [\fBLong options\fR] [\fBShell options\fR] [\fBFile\fR]

.SH DESCRIPTION

\fBkbsh\fR is a small, from-scratch POSIX shell. The session loop is driven
by a static state-transition map. The memory model uses a statically
allocated arena.

.SH OPTIONS

\fBLong options:\fR
  \fB\-\-help\fR                  Display help text and exit
  \fB\-\-version\fR               Display version information and exit

\fBShell options:\fR
  \fB\-c [string]\fR             Read commands from [string]
  \fB\-i\fR                      Run kbsh as an interactive shell
  \fB\-s\fR                      Read commands from standard input
  \fB\-abefhkmnptuvxBCHP\fR      Only used for compatibility

\fBFile:\fR
  Read commands from a plain-text file and exit

.SH COPYRIGHT

Copyright (C) 2011, 2026 Zackary Parsons.
License: GNU GPL version 3 <https://gnu.org/licenses/gpl.html>.
This is free software; you are free to change and redistribute it.
This program has NO WARRANTY, to the extent permitted by law.

.SH "BUG REPORTS"

Report bugs to: <parsons.zackary@gmail.com>
.br
Home page: <https://github.com/zstuartp/kbsh/>
